server.port: 8080

spring.datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/payments
  username: postgres
  password: postgres
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
  properties.hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    jdbc.lob.non_contextual_creation: true
logging.file: payments.log